version: '3'

services:
  docker-proxy:
    image: ghcr.io/antimatter-studios/docker-proxy:latest
    container_name: docker-proxy
    build: .
    labels:
      - docker-config-gen.request=/app/scripts/request.sh
      - docker-config-gen.response=/app/scripts/response.sh
      - docker-config-gen.renderer=nginx
    volumes:
      # DEV MODE: uncomment this to quickly edit the 200, 503 templates
      - ./html:/etc/nginx/html
      # DEV MODE: uncomment this to let you edit the entire app directory on the fly
      - ./:/app
    ports:
      - "80:80"
      - "443:443"
