version: '3'

volumes:
  docker_config_gen:
    external: true
    name: docker_config_gen

services:
  docker-proxy:
    image: antimatter-studios/docker-proxy:latest
    container_name: docker-proxy
    build:
      context: .
    labels:
      - docker-config-gen.input=/docker-proxy/nginx.tmpl
      - docker-config-gen.output=/docker-proxy/nginx.conf
      - docker-config-gen.exec="/app/reload.sh"
    volumes:
      - docker_config_gen:/config
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_CONF=/config/docker-proxy/nginx.conf

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local
